# -*- coding: utf-8 -*-
"""HuggingFace_Backup_2024_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/duskfallcrew/HuggingFace_Backup/blob/main/HuggingFace_Backup_2024_Colab.ipynb

# 🌈 HuggingFace Backup - Colab Edition

Hey there, fellow adventurers in AI! Welcome to our delightfully unique corner of the universe! ✨

## 💫 What's This All About?
This is our cozy mashup of Nocrypt's notebook and everyday AI tools, but with our own special twist! Think of it as the Colab-flavored version of our Jupyter notebook - because sometimes you need your AI magic on the go!

### 🎯 Quick Features:
- Fast uploads to HuggingFace (because waiting is overrated!)
- Focus on checkpoints (keeping it simple and sweet)
- Built for Google Colab (our cloud-powered playground)
- All the same magic as our Jupyter version, just with cloud sprinkles! ✨

## 🔍 Lost & Found
- Repo doing a disappearing act? [Find us on GitHub!](https://github.com/duskfallcrew/HuggingFace_Backup)
- CivitAI friends: Updates drop faster than a cat chasing a laser!

## ☕ Support the Magic
[![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/Z8Z8L4EO)

## 🎮 Join Our Adventure!
We're a system of 300+ alters, rocking life with DID, ADHD, Autism, and CPTSD. We believe AI can be a game-changer for mental health and creativity. Come explore with us!

### 🌟 Find Us Here:
- 🏠 [End Media](https://www.end-media.org/)
- 🎮 [Discord](https://discord.gg/5t2kYxt7An)
- 🤗 [HuggingFace](https://huggingface.co/EarthnDusk)
- 🎵 [YouTube](https://www.youtube.com/channel/UCk7MGP7nrJz5awBSP75xmVw)
- 🎪 [Reddit](https://www.reddit.com/r/earthndusk/)
- 🎨 [DeviantArt](https://www.deviantart.com/diffusionai)

### 🏴‍☠️ Special Thanks To:
- [Pirate Diffusion](https://www.piratediffusion.com/)
- [Yodayo](https://yodayo.com/)

## 💝 Credits & Cool People
Huge thanks to our code ancestors:
- EVERYDREAM2 TRAINER
- LINAQRUF
- NOCRYPT [![](https://dcbadge.vercel.app/api/shield/442099748669751297?style=flat)](https://lookup.guru/442099748669751297)

Want more AI adventures? Check out the original SD Colab:
<a target="_blank" href="https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

## 🛠️ Need Help?
- Found a bug? Don't panic! Drop by our GitHub or Discord
- Questions? We're here for you!
- Want to help? Pull requests are like hugs - always welcome!

## 🎯 Recent Updates:
1. 🌟 Enhanced Colab compatibility
2. 🔧 Streamlined file handling
3. 🎨 Made everything prettier (because we can!)
4. 📝 Clearer instructions (no more confusion!)
5. ✨ Added extra sprinkles of magic

Remember: We're not pro coders, we're creative problem solvers! Sometimes the best solutions come with a side of chaos and a sprinkle of adventure! 🌈✨

Let's make some AI magic happen! Ready to dive in? 🚀

# Google Drive Mount
"""

# @title 🚀 Connect Your Google Drive
# @markdown ## Let's Get Your Storage Powers Activated! ✨

# @markdown ### What's This All About?
# @markdown Hey there, fellow creator! Before we dive into the fun stuff, let's talk storage!

# @markdown #### 🎯 Your Options:
# @markdown 1. **Google Drive** (Recommended!)
# @markdown    - Perfect for keeping your models safe
# @markdown    - Easy access to all your files
# @markdown    - Everything stays organized
# @markdown
# @markdown 2. **Alternative Routes** (For the adventurous!)
# @markdown    - Terminal wizardry (if you're comfortable with commands)
# @markdown    - Direct uploads to Colab
# @markdown    - Other cloud storage solutions
# @markdown
# @markdown #### 🌟 Pro Tips:
# @markdown - Watch for the popup after clicking "Connect"
# @markdown - You'll need to authorize access (don't worry, it's safe!)
# @markdown - Your drive will appear as `/content/drive`

from google.colab import drive
from google.colab import output
import os

def mount_drive():
    if not os.path.exists('/content/drive'):
        print("🔮 Summoning your Google Drive...")
        drive.mount('/content/drive')
        print("\n✨ Drive mounted successfully! You're ready to rock!")
    else:
        print("🎉 Your Drive is already connected and ready to go!")

# Enable our magical widgets
output.enable_custom_widget_manager()

# Let's get that drive connected!
mount_drive()

print("""
📚 Quick Navigation Guide:
- Your Drive lives at: /content/drive
- Main workspace: /content/drive/MyDrive
- Look for the folder icon in the left sidebar

Need to upload files?
1. Find the folder icon on the left
2. Navigate to your drive
3. Drag and drop your files
4. Magic happens! ✨

Having troubles? No worries! You can:
1. Try reconnecting (run this cell again)
2. Use terminal commands if you're feeling brave
3. Direct upload to Colab (look for the folder icon!)

Remember: Your creative journey is valid, no matter which path you choose! 🌈
""")

"""# Installation & Requirements
-----------------


"""

# @title 🛠️ Installation Wizard
# @markdown ## Let's get your workspace ready for some AI magic! ✨

# @markdown ### What's in the Box?
# @markdown - HuggingFace Hub (for all your model adventures)
# @markdown - IPython Widgets (makes things pretty!)
# @markdown - Some extra goodies for file handling

print("🔍 Checking what we need...")

def check_and_install(package, install_name=None):
    import importlib
    if install_name is None:
        install_name = package
    try:
        importlib.import_module(package)
        print(f"✨ {package} is already installed!")
    except ImportError:
        print(f"📦 Installing {package}...")
        !pip install -q {install_name}

# Essential packages for our adventure!
required_packages = {
    'huggingface_hub': '--force-reinstall -q huggingface_hub',  # Fresh install for best results
    'ipywidgets': 'ipywidgets',                                 # For our lovely interface
    'glob': 'glob2'                                            # For finding files
}

# Install our magical ingredients
for package, install_cmd in required_packages.items():
    check_and_install(package, install_cmd)

# Clean up any installation messages
from IPython.display import clear_output
clear_output()

print("""
✨ All set and ready to roll! Here's what we've got cooking:

🤗 HuggingFace Hub - Your portal to model magic
🎨 IPython Widgets - Making everything pretty
📁 File Handling - Keeping things organized

If you run into any quirks or missing pieces:
1. Don't panic! We've got your back!
2. Try running this cell again
3. If things are still wonky, drop by our Discord for help!

Now, let's make some AI magic happen! 🌟
""")

# @title 🔐 Connect to HuggingFace Hub
# @markdown ## Hey there, fellow creator! Let's get you logged in! ✨

# @markdown ### Quick Guide:
# @markdown 1. First time here? Pop over to [HuggingFace](https://huggingface.co/) and create your free account!
# @markdown 2. Grab your special key from the [tokens page](https://huggingface.co/settings/tokens)
# @markdown 3. Click `New Token` (or copy an existing one with `Write` access)
# @markdown 4. Paste your magical key below and let's get this party started! 🎉

try:
    hub_ok
except NameError:
    print("✨ Setting up your HuggingFace connection...")
    !pip install --force-reinstall -qqqq huggingface_hub
    hub_ok = True

from IPython.display import clear_output
from huggingface_hub import login

# Clear any installation messages to keep things tidy
clear_output()

# @markdown ### 🔑 Your Special Access Key
write_token = "" # @param {type:"string"}

# Let's get you logged in!
try:
    login(write_token, add_to_git_credential=True)
    print("🎉 Woohoo! You're all connected and ready to rock!")
    print("💫 Your HuggingFace powers have been activated!")
except Exception as e:
    print("❌ Oops! Something's not quite right with that token.")
    print("🤔 Double-check your key and make sure it has 'Write' access!")
    print(f"🔍 Here's what went wrong: {str(e)}")
    raise

# @title 🏗️ Repository Setup Wizard
# @markdown ### Let's get your magical storage space ready! ✨

from huggingface_hub.utils import validate_repo_id, HfHubHTTPError
from huggingface_hub import HfApi

# @markdown #### 🎨 Customize Your Repository
repo_name = "Sample_Backup_Please_Rename" # @param {type:"string"}
make_private = True # @param {type:"boolean"} {description:"Keep your repo private?"}
clone_repo = True # @param {type:"boolean"} {description:"Download repo to Colab?"}

# Set up our connection to HuggingFace
api = HfApi()
user = api.whoami()
model_repo = f"{user['name']}/{repo_name.strip()}"

try:
    # Validate the repo name (just making sure it's comfy!)
    validate_repo_id(model_repo)

    # Create the repo if it doesn't exist
    api.create_repo(
        repo_id=model_repo,
        private=make_private,
        exist_ok=True  # This prevents the try/except madness!
    )
    print(f"🎉 Repository '{model_repo}' is ready for action!")

except Exception as e:
    print(f"❌ Oops! Something went wrong: {str(e)}")
    raise

# Clone the repo if requested
if clone_repo:
    print("\n📦 Downloading your repo (with some LFS magic)...")
    !git lfs install --skip-smudge
    !export GIT_LFS_SKIP_SMUDGE=1
    !git clone https://huggingface.co/{model_repo} /content/{repo_name}
    print("✨ All done! Your repo is ready to rock!")

# @title 🚀 HuggingFace File Uploader

# @markdown ## 🌟 Welcome to our File Upload Adventure!
# @markdown ### Quick Guide:
# @markdown 1. Make sure you've created a repo on HuggingFace first
# @markdown 2. Fill in your username/organization and repo name
# @markdown 3. Pick your file type from our magical dropdown
# @markdown 4. Choose whether you want a pull request or direct upload
# @markdown 5. Hit that upload button and watch the magic happen! ✨
# @markdown
# @markdown ### Pro Tips:
# @markdown - Don't see your files? Hit the "Update Files" button! 🔄
# @markdown - Want to upload multiple files? Just hold Ctrl/Cmd while clicking!
# @markdown - The commit message is customizable - make it yours! 💝

import os
import glob
import time
from pathlib import Path
from huggingface_hub import HfApi
from IPython.display import display, HTML, clear_output

# @markdown ### 📚 Repository Details
owner = "" # @param {type:"string"}
repo_name = "" # @param {type:"string"}

# @markdown ### 🗂️ File Settings
file_type = "safetensors" # @param ["safetensors", "pt", "pth", "onnx", "pb", "h5", "ckpt", "bin", "json", "yaml", "yml", "txt", "csv", "pkl", "png", "jpg", "jpeg", "webp", "gif", "zip", "tar", "gz"]
sort_by = "name" # @param ["name", "date"]

# @markdown ### 💭 Upload Settings
commit_message = "Upload with Earth & Dusk Huggingface 🤗 Backup" # @param {type:"string"}
create_pr = False # @param {type:"boolean"}
clear_after = True # @param {type:"boolean"}

def format_size(size):
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size < 1024:
            return f"{size:.2f} {unit}"
        size /= 1024
    return f"{size:.2f} TB"

def find_files():
    files = sorted(
        glob.glob(f"*.{file_type}"),
        key=os.path.getmtime if sort_by == 'date' else str
    )
    print(f"✨ Found {len(files)} {file_type} files:")
    for f in files:
        size = os.path.getsize(f)
        print(f"📁 {f} ({format_size(size)})")
    return files

def upload_files():
    if not owner or not repo_name:
        print("❗ Please fill in both Organization/Username and Repository name")
        return

    files = find_files()
    if not files:
        print("📝 No files found matching your criteria!")
        return

    api = HfApi()
    repo_id = f"{owner}/{repo_name}"
    print(f"🎯 Ready to upload to: huggingface.co/{repo_id}")
    print("Select files to upload (multiple selection supported)")

    # Show file selection interface
    from google.colab import output
    selected = output.eval_js(f"""
        const files = {files};
        const selected = await google.colab.dialog.select(files);
        selected
    """)

    if not selected:
        print("No files selected!")
        return

    total_files = len(selected)
    print(f"\n🚀 Starting upload of {total_files} files...")

    for idx, file in enumerate(selected, 1):
        size = os.path.getsize(file)
        print(f"\n📦 File {idx}/{total_files}: {file} ({format_size(size)})")

        try:
            start_time = time.time()
            response = api.upload_file(
                path_or_fileobj=file,
                path_in_repo=os.path.basename(file),
                repo_id=repo_id,
                repo_type=None,
                create_pr=create_pr,
                commit_message=commit_message
            )
            duration = time.time() - start_time
            print(f"✅ Upload completed in {duration:.1f} seconds")
        except Exception as e:
            print(f"❌ Error uploading {file}: {str(e)}")
            continue

    print("\n✨ All uploads completed! ✨")
    if create_pr:
        print("🎉 Check your repository for the new Pull Request!")
    else:
        print("🎉 Files have been uploaded directly to your repository!")

    if clear_after:
        time.sleep(3)
        clear_output()

# Add our friendly buttons
from IPython.display import HTML
display(HTML('''
<style>
.button-container {
    display: flex;
    gap: 10px;
    margin: 20px 0;
}
.custom-button {
    padding: 10px 20px;
    border-radius: 8px;
    border: none;
    cursor: pointer;
    font-size: 16px;
    transition: all 0.3s;
}
.update-btn {
    background-color: #3498db;
    color: white;
}
.upload-btn {
    background-color: #2ecc71;
    color: white;
}
.custom-button:hover {
    transform: translateY(-2px);
    box-shadow: 0 5px 15px rgba(0,0,0,0.1);
}
</style>
<div class="button-container">
    <button class="custom-button update-btn" onclick="google.colab.kernel.invokeFunction('find_files', [], {})">🔄 Update Files</button>
    <button class="custom-button upload-btn" onclick="google.colab.kernel.invokeFunction('upload_files', [], {})">⬆️ Upload Files</button>
</div>
'''))

# Register our functions
from google.colab.output import eval_js
output.register_callback('find_files', find_files)
output.register_callback('upload_files', upload_files)

# Show initial file list
find_files()