# -*- coding: utf-8 -*-
"""HuggingFace_Backup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HWCsjAL9sH3lpb-5YW8xzQNNqz_G5eNq

# **Hugging Face Backup**
<small> An extremely weird fork of content from Nocrypt's notebook by a DID system that has no clue how to code. We'd call it opinionated, but it's not a WebUI, so apart from ElFinder, free users should be able to use this.

## ***❤❤❤❤❤❤❤❤❤❤❤***
*Quickly upload stuff like merged models to huggingface*
-----------------
<small>Code yoinked from Nocrypt, notebook literally just has his credits in there because we wanted a seperate notebook for backups besides just the stable diffusion settings. This includes some extra toys like Imjoy-Elfinder and Google Drive mount. We don't know how to code, and there may not be a TON of updates on this.



-----------------
## ♦♦ **COLAB UPDATES** ♦♦
If you've copied this to drive and it's no longer working check here: https://github.com/kieranxsomer/HuggingFace_Backup
-----------------
### ✅ **Mount Drive!**
This is extremely optional, but y'know if you need it!

-----------------

### ✅ **Imjoy-Elfinder**

An optional file viewer that may give you a more visual way of looking at your files. Also good if you need to upload files instead of using terminal or gdrive.

-----------------

###  ✅ **Hugging Face Hub Options**

☢☢ **How to use this colab** ☢☢

Scream, because i couldn't get "THE FUN WAY" To work.
Which is OK,  because the "MANUAL" way is faster.
There is no need to actually fix code, or anything just copy and paste your details as instructed.

☢☢ **MAKE SURE:** ☢☢

You create a huggingface token, go to [this link](https://huggingface.co/settings/tokens), then `create new token` or copy available token with the `Write` role.

🔼 Run cell `1,2,3`

You only need to choose one between `3.2,and 3.3`

Note 3.1 was yoinked because right now I don't know how to patch it to work outside of a stable diffusion instance.  If you're using a free colab, try not to use the File Finder - as that's probably considerd a "REMOTE UI"

Make sure you `MOUNT` your google drive, I've patched in `Imjoy-Elfinder` for kicks. - Visual people like this, I know I do.

-----------------
**<small> *Forked from LYNN - AND NOCRYPT - Literally just yoinked it from this notebook:* https://colab.research.google.com/drive/1wEa-tS10h4LlDykd87TF5zzpXIIQoCmq**

-----------------
**WE TAKE NO CREDIT ON THIS. FOLLOW NOCRYPTS STUFF HERE:**

[![](https://dcbadge.vercel.app/api/shield/442099748669751297?style=flat)](https://lookup.guru/442099748669751297) [![ko-fi](https://img.shields.io/badge/Ko--fi-F16061?logo=ko-fi&logoColor=white&style=flat)](https://ko-fi.com/nocrypt) [![ko-fi](https://img.shields.io/badge/Patreon-F1465A?logo=patreon&logoColor=white&style=flat)](https://patreon.com/nocrypt)


☢ <small> You can find updates on NoCrypt's toys: https://discord.gg/touhouai

☢ <small> Earth & Dusk Discord because REASONS: https://discord.gg/5t2kYxt7An

-----------------

# Google Drive Mount
<small> If you're NOT using drive, but have a way of uploading your files via command line - use the Imjoy-Elfinder section below.
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Imjoy-Elfinder (Optional)
<small> Useful if you need to check where files are OR you're not using google drive and have uploaded your files already.
"""

!pip install imjoy-elfinder

import threading
from google.colab import output
from imjoy_elfinder.app import main

# start imjoy-elfinder server
thread = threading.Thread(target=main, args=[["--root-dir=/content", "--port=8765"]])
thread.start()

# view the
output.serve_kernel_port_as_iframe(8765, height='800')

# open imjoy-elfinder in a new tab
output.serve_kernel_port_as_window(8765)

"""# Upload to Huggingface Hub (FUN WAY)

"""

#@title 1. Login to Huggingface hub
try:
  hub_ok # My packaged dep didn't contains this (but stil have the folder)
except:
  print("Setting up huggingface_hub...")
  !pip install --force-reinstall -qqqq huggingface_hub
  hub_ok = True
from IPython.display import clear_output
from huggingface_hub import login
clear_output()

#@markdown 1. Of course, you need a Huggingface account first.
#@markdown 2. To create a huggingface token, go to [this link](https://huggingface.co/settings/tokens), then `create new token` or copy available token with the `Write` role.

write_token = "" #@param {type:"string"}
login(write_token, add_to_git_credential=True)

#@title 2. Setup Repo
from huggingface_hub.utils import validate_repo_id, HfHubHTTPError
from huggingface_hub import HfApi


api = HfApi()
user = api.whoami(write_token)

#@markdown #### If your model repo didn't exist, it will automatically create your repo.
repo_name = "my_entirely_stupid_backup_you_might_wanna_rename_this_section" #@param{type:"string"}
make_this_repo_private_if_not_exist = False #@param{type:"boolean"}
clone_with_git = True #@param{type:"boolean"}

model_repo = user['name']+"/"+repo_name.strip()

validate_repo_id(model_repo)

if repo_name != "":
  try:
      api.create_repo(repo_id=model_repo,
                      private=make_this_repo_private_if_not_exist)
      print("Model Repo didn't exists, creating repo")
      print("Model Repo: ",model_repo,"created!\n")

  except HfHubHTTPError as e:
      print(f"Model Repo: {model_repo} exists, skipping create repo\n")

if clone_with_git:
  !git lfs install --skip-smudge
  !export GIT_LFS_SKIP_SMUDGE=1
  !git clone https://huggingface.co/{model_repo} /content/{repo_name}

"""# Manual Huggingface Uploads

"""

#@title 3.2 Upload via huggingface_hub (Manual way)
#@markdown If these are not your folder settings, feel free to just copy the path like you would have for the above "FUN WAY" section.

#@markdown All paths for easier access:<br>
#@markdown /content/sdw/models/Stable-diffusion<br>
#@markdown /content/sdw/models/VAE<br>
#@markdown /content/sdw/models/Lora<br>
#@markdown /content/sdw/embeddings<br>
#@markdown /content/sdw/models/hypernetwork<br>
from huggingface_hub import HfApi
from pathlib import Path

api = HfApi()
file_path = "/content/models/Anything-V3-vae-swapped.safetensors" #@param {type :"string"}
commit_message = "Upload with 🚀🤗 NoCrypt's HUGGING FACE backup - Yoinked by Earth & Dusk" #@param {type :"string"}

if file_path != "":
  path_obj = Path(file_path)
  trained_model = path_obj.parts[-1]

  print(f"Uploading {trained_model} to https://huggingface.co/"+model_repo)
  print(f"Please wait...")

  api.upload_file(
      path_or_fileobj=file_path,
      path_in_repo=trained_model,
      repo_id=model_repo,
      commit_message=commit_message,
  )

  print(f"Upload success, located at https://huggingface.co/"+model_repo+"/blob/main/"+trained_model+"\n")

"""# Upload Via GIT (supposedly more stable)"""

# Commented out IPython magic to ensure Python compatibility.
#@title 3.3 Upload via GIT (more stable)
# %cd /content/
file_path = "/content/models/Anything-V3-vae-swapped.safetensors" #@param {type :"string"}
!ln {file_path} /content/{repo_name}/
#@markdown Set **git commit identity**
email = "your-email" #@param {'type': 'string'}
name = "your-username" #@param {'type': 'string'}
#@markdown Set **commit message**
commit_m = "Upload with 🚀🤗 NoCrypt's HUGGING FACE backup - Yoinked by Earth & Dusk" #@param {'type': 'string'}

# %cd /content/{repo_name}

!git lfs install --skip-smudge
!export GIT_LFS_SKIP_SMUDGE=1
!git pull -X theirs

!git lfs install
!huggingface-cli lfs-enable-largefiles .
!git config --global user.email "{email}"
!git config --global user.name "{name}"
!git add .
!git commit -m "{commit_m}"
!git push